/**
 * Checkbox РРО API Client
 *
 * Checkbox is a cloud-based fiscal receipt system (програмний РРО) required by Ukrainian law.
 * Docs: https://dev.checkbox.ua/doc/api/
 */

import {
	CHECKBOX_LICENSE_KEY,
	CHECKBOX_CASH_REGISTER_ID,
	CHECKBOX_LOGIN,
	CHECKBOX_PASSWORD,
	CHECKBOX_PIN_CODE,
	CHECKBOX_PRODUCTION
} from '$env/static/private';

interface CheckboxConfig {
	login?: string;
	password?: string;
	licenseKey: string;
	pinCode?: string; // Recommended authentication method
	cashRegisterId?: string;
	isProduction?: boolean;
}

interface CheckboxAuthResponse {
	access_token: string;
	token_type: string;
}

interface CheckboxReceiptItem {
	code: string; // Product code/SKU (duplicate of good.code for convenience)
	good: {
		code: string; // Product code/SKU
		name: string; // Product name
		price: number; // Price in kopiykas
		tax?: number[] | string[]; // Tax codes/rates
		barcode?: string; // Product barcode
		header?: string; // Product header
		footer?: string; // Product footer
		uktzed?: string; // UKTZED code
	};
	name: string;
	price: number; // Price in kopiykas (cents)
	quantity: number; // Quantity in thousands (1 unit = 1000)
	discount?: any[];
	is_return?: boolean;
}

interface CheckboxReceiptPayment {
	type: 'CASHLESS'; // Безготівка (card payment)
	value: number; // Amount in kopiykas
}

interface CreateReceiptRequest {
	id?: string; // UUID of the receipt (optional, can be auto-generated by API)
	cashier_name?: string; // Cashier name
	departament?: string; // Department name
	goods: CheckboxReceiptItem[];
	payments: CheckboxReceiptPayment[];
	delivery?: {
		email?: string;
		emails?: string[];
		phone?: string;
	};
	order_id?: string; // External order ID
	discounts?: any[];
	header?: string;
	footer?: string;
}

interface CheckboxReceiptResponse {
	id: string;
	type: string;
	serial: number;
	status: string;
	fiscal_code: string;
	fiscal_date: string;
	total_sum: number;
	total_payment: number;
	delivered_at?: string;
	created_at: string;
	updated_at: string;
	related_receipt_id?: string;
	receipt_url?: string;
	tax_url?: string;
}

interface CheckboxShiftResponse {
	id: string;
	serial: number;
	status: string;
	opened_at: string;
	closed_at?: string;
	initial_transaction_id?: string;
	closing_transaction_id?: string;
	cash_register: {
		id: string;
		fiscal_number: string;
		number: number;
		active: boolean;
		created_at: string;
		updated_at: string;
	};
	created_at: string;
	updated_at: string;
	balance?: {
		cash: number;
		cashless: number;
	};
}

interface CheckboxCashierInfo {
	id: string;
	full_name: string;
	email: string;
	permissions: string[];
	roles: string[];
	organization: {
		id: string;
		name: string;
	};
}

interface CheckboxCashRegister {
	id: string;
	fiscal_number: string;
	name: string;
	address: string;
	organization_id: string;
	created_at: string;
	updated_at: string;
}

export class CheckboxClient {
	private login?: string;
	private password?: string;
	private licenseKey: string;
	private pinCode?: string;
	private cashRegisterId?: string;
	private baseUrl: string;
	private accessToken: string | null = null;
	private tokenExpiry: number = 0;

	constructor(config: CheckboxConfig) {
		this.login = config.login;
		this.password = config.password;
		this.licenseKey = config.licenseKey;
		this.pinCode = config.pinCode;
		this.cashRegisterId = config.cashRegisterId;
		this.baseUrl = config.isProduction
			? 'https://api.checkbox.ua/api/v1'
			: 'https://api.checkbox.ua/api/v1';
	}

	/**
	 * Authenticate with Checkbox API using PIN code (recommended method)
	 * Docs: https://wiki.checkbox.ua/api/auth
	 */
	private async authenticateWithPinCode(): Promise<void> {
		if (!this.pinCode) {
			throw new Error('PIN code not provided for authentication');
		}

		const response = await fetch(`${this.baseUrl}/cashier/signinPinCode`, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				'X-License-Key': this.licenseKey
			},
			body: JSON.stringify({
				pin_code: this.pinCode
			})
		});

		if (!response.ok) {
			const error = await response.json();
			throw new Error(
				`Checkbox PIN authentication failed: ${error.message || response.statusText}`
			);
		}

		const data = (await response.json()) as CheckboxAuthResponse;
		this.accessToken = data.access_token;
		// Set token expiry to 1 hour from now (JWT tokens don't have explicit expiry from API)
		this.tokenExpiry = Date.now() + 3600000;
	}

	/**
	 * Authenticate with Checkbox API using login/password (fallback method)
	 * Docs: https://wiki.checkbox.ua/api/auth
	 */
	private async authenticateWithCredentials(): Promise<void> {
		if (!this.login || !this.password) {
			throw new Error('Login and password not provided for authentication');
		}

		const response = await fetch(`${this.baseUrl}/cashier/signin`, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({
				login: this.login,
				password: this.password
			})
		});

		if (!response.ok) {
			const error = await response.json();
			throw new Error(`Checkbox authentication failed: ${error.message || response.statusText}`);
		}

		const data = (await response.json()) as CheckboxAuthResponse;
		this.accessToken = data.access_token;
		// Set token expiry to 1 hour from now (JWT tokens don't have explicit expiry from API)
		this.tokenExpiry = Date.now() + 3600000;
	}

	/**
	 * Authenticate with Checkbox API
	 * Tries PIN code first (recommended), falls back to login/password
	 */
	private async authenticate(): Promise<void> {
		// Check if token is still valid
		if (this.accessToken && Date.now() < this.tokenExpiry - 60000) {
			return; // Token valid for at least 1 more minute
		}

		// Try PIN code authentication first (recommended method)
		if (this.pinCode) {
			await this.authenticateWithPinCode();
			return;
		}

		// Fall back to login/password authentication
		if (this.login && this.password) {
			await this.authenticateWithCredentials();
			return;
		}

		throw new Error('No authentication credentials provided (PIN code or login/password required)');
	}

	/**
	 * Make authenticated request to Checkbox API
	 */
	private async request<T>(endpoint: string, options: RequestInit = {}): Promise<T> {
		await this.authenticate();

		const response = await fetch(`${this.baseUrl}${endpoint}`, {
			...options,
			headers: {
				...options.headers,
				Authorization: `Bearer ${this.accessToken}`,
				'Content-Type': 'application/json',
				'X-License-Key': this.licenseKey
			}
		});

		if (!response.ok) {
			console.log('Checkbox API request failed:', {
				endpoint,
				status: response.status,
				body: await response.text()
			});
			const error = await response.json().catch(() => ({ message: response.statusText }));

			// If token is invalid, clear it and retry once
			if (
				(error.message?.includes('Невірний токен') || response.status === 401) &&
				this.accessToken
			) {
				this.accessToken = null;
				this.tokenExpiry = 0;
				return this.request<T>(endpoint, options);
			}

			throw new Error(`Checkbox API error: ${error.message || response.statusText}`);
		}

		console.log('Checkbox API request successful:', { endpoint, status: response.status, response });

		return (await response.json()) as T;
	}

	/**
	 * Make authenticated request to Checkbox API for raw responses (non-JSON)
	 * Handles binary data (PNG) and text responses
	 */
	private async requestRaw(endpoint: string, options: RequestInit = {}): Promise<string> {
		await this.authenticate();

		const response = await fetch(`${this.baseUrl}${endpoint}`, {
			...options,
			headers: {
				...options.headers,
				Authorization: `Bearer ${this.accessToken}`,
				'X-License-Key': this.licenseKey
			}
		});

		if (!response.ok) {
			console.log('Checkbox API raw request failed:', {
				endpoint,
				status: response.status,
				body: await response.text()
			});

			// If token is invalid, clear it and retry once
			if (response.status === 401 && this.accessToken) {
				this.accessToken = null;
				this.tokenExpiry = 0;
				return this.requestRaw(endpoint, options);
			}

			throw new Error(`Checkbox API error: ${response.statusText}`);
		}

		const contentType = response.headers.get('content-type');
		console.log('Checkbox API raw request successful:', { endpoint, status: response.status, contentType });

		// For PNG images, return base64-encoded string
		if (contentType?.includes('image/png')) {
			const buffer = await response.arrayBuffer();
			return Buffer.from(buffer).toString('base64');
		}

		// For text and HTML, return as plain text
		return await response.text();
	}

	/**
	 * Sign out (deactivate current token)
	 * Docs: https://wiki.checkbox.ua/api/auth
	 */
	async signout(): Promise<void> {
		if (!this.accessToken) {
			return; // Already signed out
		}

		try {
			await this.request('/cashier/signout', {
				method: 'POST',
				body: JSON.stringify({})
			});
		} finally {
			// Clear token regardless of response
			this.accessToken = null;
			this.tokenExpiry = 0;
		}
	}

	/**
	 * Get current cashier info
	 */
	async getCashierInfo(): Promise<CheckboxCashierInfo> {
		return await this.request<CheckboxCashierInfo>('/cashier/me', {
			method: 'GET'
		});
	}

	/**
	 * Get current open shift
	 */
	async getCurrentShift(): Promise<CheckboxShiftResponse | null> {
		try {
			const shifts = await this.request<{ results: CheckboxShiftResponse[] }>('/shifts', {
				method: 'GET'
			});

			const openShift = shifts.results.find((s) => s.status === 'OPENED');
			return openShift || null;
		} catch {
			return null;
		}
	}

	/**
	 * Open new shift (касова зміна)
	 */
	async openShift(): Promise<CheckboxShiftResponse> {
		return await this.request<CheckboxShiftResponse>('/shifts', {
			method: 'POST',
			body: JSON.stringify({})
		});
	}

	/**
	 * Close current shift
	 */
	async closeShift(): Promise<CheckboxShiftResponse> {
		const currentShift = await this.getCurrentShift();

		if (!currentShift) {
			throw new Error('No open shift found');
		}

		return await this.request<CheckboxShiftResponse>(`/shifts/${currentShift.id}/close`, {
			method: 'POST',
			body: JSON.stringify({})
		});
	}

	/**
	 * Create sale receipt (чек продажу)
	 */
	async createSaleReceipt(data: CreateReceiptRequest): Promise<CheckboxReceiptResponse> {
		// Ensure shift is open
		let shift = await this.getCurrentShift();

		if (!shift) {
			shift = await this.openShift();
		}

		return await this.request<CheckboxReceiptResponse>('/receipts/sell', {
			method: 'POST',
			body: JSON.stringify(data)
		});
	}

	/**
	 * Create return receipt (чек повернення)
	 */
	async createReturnReceipt(data: CreateReceiptRequest): Promise<CheckboxReceiptResponse> {
		// Ensure shift is open
		let shift = await this.getCurrentShift();

		if (!shift) {
			shift = await this.openShift();
		}

		return await this.request<CheckboxReceiptResponse>('/receipts/return', {
			method: 'POST',
			body: JSON.stringify(data)
		});
	}

	/**
	 * Get receipt by ID
	 */
	async getReceipt(receiptId: string): Promise<CheckboxReceiptResponse> {
		return await this.request<CheckboxReceiptResponse>(`/receipts/${receiptId}`, {
			method: 'GET'
		});
	}

	/**
	 * Get receipt text (for printing)
	 * Returns plain text representation of the receipt
	 */
	async getReceiptText(receiptId: string): Promise<string> {
		return await this.requestRaw(`/receipts/${receiptId}/text`, {
			method: 'GET'
		});
	}

	/**
	 * Get receipt HTML
	 * Returns HTML representation of the receipt
	 */
	async getReceiptHtml(receiptId: string): Promise<string> {
		return await this.requestRaw(`/receipts/${receiptId}/html`, {
			method: 'GET'
		});
	}

	/**
	 * Get receipt PNG image
	 * Returns base64-encoded PNG image
	 */
	async getReceiptPng(receiptId: string): Promise<string> {
		return await this.requestRaw(`/receipts/${receiptId}/png`, {
			method: 'GET'
		});
	}

	/**
	 * Get cash register info
	 */
	async getCashRegisterInfo(cashRegisterId?: string): Promise<CheckboxCashRegister> {
		const id = cashRegisterId || this.cashRegisterId;

		if (!id) {
			throw new Error('Cash register ID not provided');
		}

		return await this.request<CheckboxCashRegister>(`/cash-registers/${id}`, {
			method: 'GET'
		});
	}

	/**
	 * Get all cash registers for cashier
	 */
	async getCashRegisters(): Promise<CheckboxCashRegister[]> {
		const response = await this.request<{ results: CheckboxCashRegister[] }>('/cash-registers', {
			method: 'GET'
		});

		return response.results;
	}
}

/**
 * Get Checkbox client instance
 *
 * Supports two authentication methods (in order of preference):
 * 1. PIN code + License key (recommended): CHECKBOX_PIN_CODE + CHECKBOX_LICENSE_KEY
 * 2. Login + Password (fallback): CHECKBOX_LOGIN + CHECKBOX_PASSWORD
 */
export function getCheckboxClient(): CheckboxClient {
	const licenseKey = CHECKBOX_LICENSE_KEY;
	const pinCode = CHECKBOX_PIN_CODE;
	const login = CHECKBOX_LOGIN;
	const password = CHECKBOX_PASSWORD;
	const cashRegisterId = CHECKBOX_CASH_REGISTER_ID;
	const isProduction = CHECKBOX_PRODUCTION === 'true';

	if (!licenseKey) {
		throw new Error(
			'Checkbox credentials not configured. Set CHECKBOX_LICENSE_KEY environment variable.'
		);
	}

	// Check that at least one authentication method is provided
	if (!pinCode && (!login || !password)) {
		throw new Error(
			'Checkbox authentication not configured. Provide either CHECKBOX_PIN_CODE (recommended) or both CHECKBOX_LOGIN and CHECKBOX_PASSWORD environment variables.'
		);
	}

	return new CheckboxClient({
		licenseKey,
		pinCode,
		login,
		password,
		cashRegisterId,
		isProduction
	});
}
